spring:
  application:
    host: ${URL_SHORTENER_HOST:localhost}
    name: url-shortener
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    mongodb:
      uri: mongodb://${MONGO_DB_USERNAME:mongoadmin}:${MONGO_DB_PASSWORD:root}@localhost:27017/admin

  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
  config:
    import: "optional:consul:"

redis:
  global:
    counter:
      key: ${REDIS_GLOBAL_COUNTER_KEY:global_counter_key}
  bloom:
    filter:
      key: ${BLOOM_FILTER_KEY:custom_alias}
    init:
      key: ${BLOOM_FILTER_CREATED:bloom_filter_created}
  short:
    long:
      url:
        mapping:
          key: ${REDIS_SHORT_LONG_URL_MAPPING_KEY:short_long_url_mapping}